mist:
  #Base_url should only need to be changed if using another mist environment for example the American one
  base_url: https://api.eu.mist.com/api/v1
  org_id:
  mist_token:
  #Configuration of your MIST environment
  config:
    #get rftemplate_id from {base_url}/orgs/{org_id}/rftemplates
    rftemplate_id:
    country:
    #Site-template for import of sites get from {base_url}/sites/{site_id}/setting
    #Where site_id is an existing site you want to copy settings from
    auto_upgrade:
      enabled: True
      version: custom
      time_of_day: 02:00
      custom_versions:
        AP33: 0.8.21202
        AP43: 0.8.21202
      day_of_week: any
    rtsa:
      enabled: true
      track_asset: true
      app_waking: true
    led:
      enabled: true
      brightness: 255
    wifi:
      enabled: true
      locate_unconnected: true
      mesh_enabled:
      detect_interference:
    wootcloud: null
    skyatp:
      enabled:
      send_ip_mac_mapping:
    persist_config_on_device: true
    engagement:
      dwell_tags:
        passerby: 1-300
        bounce: 301-14400
        engaged: 14401-28800
        stationed: 28801-42000
      dwell_tag_names:
        passerby:
        bounce:
        engaged:
        stationed:
      hours:
        sun: null
        mon: null
        tue: null
        wed: null
        thu: null
        fri: null
        sat: null
    analytic:
      enabled: true
    rogue:
      min_rssi: -80
      min_duration: 10
      enabled: true
      honeypot_enabled: true
      whitelisted_bssids:
      -
      whitelisted_ssids:
      -
    ssh_keys: []
    vars: {}
    wids: {}
    mxtunnel:
      enabled:
      vlan_ids: []
      ap_subnets:
      -
      mtu: 0
      protocol: udp
      clusters: []
    occupancy:
      min_duration: 300
      clients_enabled: true
      sdkclients_enabled: true
      assets_enabled: true
      unconnected_clients_enabled: true
    gateway_mgmt:
      app_usage: true


report:
  regex_sitename: .*\(....\)
  file_path: reports/
  filename: Inventory_

import:
  import_file: import-mall.xlsx
  import_sheet: Sites
  show_more_details: True

  #Google api for geolocation in create site-script
google:
  google_api_key:
